### ISSUE TITLE
Add translation for usage sections

### ISSUE THREAD

**Issue by mondeja** [mondeja/shread#27]
## Example

Most complex usage section case:

<details>
<summary>Mako input to parse</summary>

```mako
<%block name="usage_desc">
  Install PostgreSQL packages and, optionally, some additional packages from official sources.
  Also check if the postgres service is running and enables it, if not already, for execute at start.
</%block>
<%block name="usage_opts_desc">
  -pgv POSTGRESQL_VERSION, --postgresql-version POSTGRESQL_VERSION
                                    PostgreSQL version to install. If not provided, the latest version in repositories will be installed.
  -gis, --install-postgis           Install Postgis package correspondent to the PostgreSQL version to install.
  -gisv POSTGIS_VERSION, --postgis-version POSTGIS_VERSION
                                    Specifies what version of PostGIS will be installed. Only has effect passing '--install-postgis' option.
                                    If not provided, will be installed the latest available version of the package.
  -pgad, --install-pgadmin          Install latest version available of 'pgadmin' package.
  -plpy3, --install-plpython3       Install latest version available of 'postgresql-plpython3-*' package.
</%block>
```

</details>

<details>
<summary>Bash script to replace</summary>

```bash
function usage {
    cat <<HELP_USAGE
Usage: unix/debian/install/postgresql/$_SCRIPT_FILENAME [-h] [-i STRING] [-pgv POSTGRESQL_VERSION] [-gis] [-gisv POSTGIS_VERSION] [-pgad] [-plpy3]

  Install PostgreSQL packages and, optionally, some additional packages from official sources.
  Also check if the postgres service is running and enables it, if not already, for execute at start.

Options:
  -h, --help                        Show this help message and exit.
  -i STRING, --indent STRING        Each line of the script output will be preceded with the string defined in this parameter.
  -pgv POSTGRESQL_VERSION, --postgresql-version POSTGRESQL_VERSION
                                    PostgreSQL version to install. If not provided, the latest version in repositories will be installed.
  -gis, --install-postgis           Install Postgis package correspondent to the PostgreSQL version to install.
  -gisv POSTGIS_VERSION, --postgis-version POSTGIS_VERSION
                                    Specifies what version of PostGIS will be installed. Only has effect passing '--install-postgis' option.
                                    If not provided, will be installed the latest available version of the package.
  -pgad, --install-pgadmin          Install latest version available of 'pgadmin' package.
  -plpy3, --install-plpython3       Install latest version available of 'postgresql-plpython3-*' package.

HELP_USAGE
    exit 1
}
```

</details>

<details>
<summary>Help</summary>

```
Usage: unix/debian/install/postgresql/es.sh [-h] [-i STRING] [-pgv POSTGRESQL_VERSION] [-gis] [-gisv POSTGIS_VERSION] [-pgad] [-plpy3]

  Install PostgreSQL packages and, optionally, some additional packages from official sources.
  Also check if the postgres service is running and enables it, if not already, for execute at start.

Options:
  -h, --help                        Show this help message and exit.
  -i STRING, --indent STRING        Each line of the script output will be preceded with the string defined in this parameter.
  -pgv POSTGRESQL_VERSION, --postgresql-version POSTGRESQL_VERSION
                                    PostgreSQL version to install. If not provided, the latest version in repositories will be installed.
  -gis, --install-postgis           Install Postgis package correspondent to the PostgreSQL version to install.
  -gisv POSTGIS_VERSION, --postgis-version POSTGIS_VERSION
                                    Specifies what version of PostGIS will be installed. Only has effect passing '--install-postgis' option.
                                    If not provided, will be installed the latest available version of the package.
  -pgad, --install-pgadmin          Install latest version available of 'pgadmin' package.
  -plpy3, --install-plpython3       Install latest version available of 'postgresql-plpython3-*' package.
```

</details>

## TODO

- [x] Add `Usage:` and `Options:` to compendium as msgids (must not be removed if not found in scripts).
- [x] Add `Show this help message and exit.` to compendium.
- [x] Add `Each line of the script output will be preceded with the string defined in this parameter.` to compendium.
- [x] Parse `usage_desc` blocks. Every newline must be a different msgid.
- [x] Parse `usage_opts_desc` blocks descriptions. Every newline must be a different msgid.
- [x] Replace messages in Bash script:
  - [x] `Usage:`.
  - [x] `Options:`.
  - [x] `Show this help message and exit.`.
  - [x] `Each line of the script output will be preceded with the string defined in this parameter.`.
  - [x] Script description.
  - [x] Options descriptions.
